# Use the official Node.js 16 image as a parent image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

EXPOSE 8080

# Keep the container running
CMD ["tail", "-f", "/dev/null"]